apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- deployment.yaml
- horizontal-pod-autoscaler.yaml
- service.yaml

images:
- name: docker.io/istio/proxyv2
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/proxyv2
