---
apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  labels:
    serving.knative.dev/release: "v0.11.1"
  name: queue-proxy
  namespace: knative-serving
spec:
  image: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-queue:792f6945


