apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- apiservice.yaml
- image.yaml
- hpa.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-activator
  newTag: 8e606671
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-autoscaler-hpa
  newTag: 5e0fadf5
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-autoscaler
  newTag: ef1f01b5
- name: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-istio
  newTag: 727a623c
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-webhook
  newTag: 1ef33282
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: registry-vpc.cn-hangzhou.aliyuncs.com/hellobike-public/knative-controller
  newTag: 5ca13e5b
