apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-aiplatform-default
  namespace: anonymous
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-aiplatform-default
  namespace: anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-aiplatform-default
subjects:
- kind: ServiceAccount
  name: default
  namespace: aiplatform
- kind: ServiceAccount
  name: default-editor
  namespace: anonymous
